version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: receipt-insights-redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: receipt-insights-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: receipt-insights-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

volumes:
  redis_data: